document.addEventListener("keyup",function (e){var key=e.key+e.location;if(key=="Shift2")if(main.style.visibility=="hidden"){main.style.visibility="visible";console.style.visibility="visible"}else{main.style.visibility="hidden";console.style.visibility="hidden"}})
var iframe=document.createElement('iframe')
iframe.setAttribute('src',"https://d24495be-71d8-4db5-95db-cfddefe5ecc0.id.repl.co")
iframe.setAttribute('style','scrollbar:none;position:relative;width:100%;height:100%;top:0px;right:0px;border:none;overflow:hidden')
appid.appendChild(iframe)
